NUMPY CRASH COURSE

In [4]:
import numpy as np
from numpy import * # internally it called all 217 functions

In [5]:
np.__version__

'1.21.5'

CREATING ARRAYS

In [6]:
MY_LIST=[0,1,2,3,4,5]
MY_LIST

[0, 1, 2, 3, 4, 5]

In [7]:
type(MY_LIST)

list

In [8]:
arr=np.array(MY_LIST)

In [9]:
arr

array([0, 1, 2, 3, 4, 5])

In [10]:
type(arr)

numpy.ndarray

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(3.0)

array([0., 1., 2.])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(0,5,4,3) # atleast one argument and max is three allowed

TypeError: Cannot interpret '3' as a data type

In [ ]:
np.arange(10,20)

In [ ]:
np.arange(20,10) # first element should always less than second element.
# giving empty array

In [ ]:
np.arange(-10,10)

In [ ]:
np.arange(-10,10,5)

In [ ]:
np.arange(30,20) # ist arg always be < than 2nd arg

In [ ]:
b=np.arange(-30,20)

In [ ]:
b

In [ ]:
type(b)

In [ ]:
dtype(b)

In [ ]:
np.arange(10,10)

ZEROS

In [ ]:
b1=np.zeros(2)
b1

In [ ]:
np.zeros(5,dtype=int)

In [ ]:
z=np.zeros((2,2),dtype=int)
z

In [ ]:
np.zeros((10,10))

In [ ]:
np.zeros((3,3))

In [ ]:
np.zeros((3,3),dtype=int)

In [ ]:
np.zeros((10,30))

In [ ]:
np.zeros((5,10)) #first arg is row and second arg is columns

In [ ]:
n=(5,7)
n2=(6,8)
print(np.zeros(n)) # parameter tunning
print(np.zeros(n,dtype=int)) # hyperparameter tunning

In [ ]:
print(np.zeros(n2))

ONES

In [ ]:
np.ones(4,dtype=int)

In [ ]:
np.ones(5)

In [ ]:
n

In [ ]:
np.ones(n)

In [ ]:
np.ones(n,dtype=int)

In [ ]:
np.twos((2,3))

In [ ]:
np.ones((2,4))

In [ ]:
np.ones((2,4),dtype=int)

In [ ]:
np.arange(3)

In [ ]:
range(13)

In [ ]:
list(range(13))

In [ ]:
l=list(range(10))

In [ ]:
for i in l:
    print(i)

In [ ]:
rand(3,2)

In [17]:
random.rand(3,2)

array([[0.42808477, 0.41810132],
       [0.10238094, 0.47639031],
       [0.27035079, 0.82071801]])

In [18]:
np.random.rand(3,2)

array([[0.55074089, 0.33741972],
       [0.52027549, 0.82295596],
       [0.65745521, 0.88923904]])

In [19]:
np.random.rand(4)

array([0.7656437 , 0.53094191, 0.47366104, 0.9190637 ])

In [20]:
np.random.rand(2,4)

array([[0.08111088, 0.63899197, 0.33559506, 0.57320461],
       [0.50368307, 0.9292677 , 0.12790421, 0.91057657]])

In [21]:
np.random.rand(2,20) # 2nd element is exclusive

array([[0.75129272, 0.44282938, 0.87242498, 0.95547855, 0.24308866,
        0.28330189, 0.8612395 , 0.79125627, 0.93432418, 0.85231742,
        0.23676503, 0.94254425, 0.87442286, 0.84203493, 0.64113035,
        0.49900525, 0.22532717, 0.27778469, 0.73393245, 0.65533081],
       [0.07638577, 0.83513709, 0.44949217, 0.48336012, 0.58808807,
        0.7416432 , 0.06701474, 0.32850438, 0.01091036, 0.12932609,
        0.77905962, 0.56377533, 0.80801884, 0.57160674, 0.86407112,
        0.3970297 , 0.11474965, 0.35975264, 0.32393918, 0.56785342]])

In [22]:
np.random.randint(0,2)

1

In [23]:
np.random.randint(1,10,4)

array([2, 9, 9, 6])

In [24]:
np.random.randint(30,30,10)

ValueError: low >= high

In [25]:
np.random.randint(1)

0

In [26]:
np.random.randint(5,9)

8

In [28]:
np.random.randint(10,21,5)

array([19, 11, 17, 10, 11])

In [29]:
np.random.randint(10,40,(10,10))

array([[25, 13, 10, 31, 22, 26, 28, 33, 15, 33],
       [27, 22, 24, 33, 31, 17, 38, 38, 13, 21],
       [38, 22, 20, 38, 37, 32, 28, 39, 16, 31],
       [24, 15, 37, 33, 20, 13, 21, 34, 12, 19],
       [11, 31, 33, 36, 13, 18, 21, 16, 39, 16],
       [11, 34, 12, 10, 28, 24, 31, 37, 38, 19],
       [39, 21, 21, 17, 21, 28, 32, 17, 39, 28],
       [16, 20, 20, 21, 36, 38, 17, 12, 14, 28],
       [15, 29, 17, 23, 20, 16, 31, 17, 30, 22],
       [12, 30, 14, 31, 14, 25, 32, 19, 19, 24]])

In [30]:
b=np.random.randint(10,20,(5,4))

In [31]:
b

array([[19, 15, 19, 17],
       [11, 11, 11, 15],
       [15, 13, 11, 12],
       [10, 19, 10, 19],
       [13, 17, 19, 10]])

In [32]:
b[:]

array([[19, 15, 19, 17],
       [11, 11, 11, 15],
       [15, 13, 11, 12],
       [10, 19, 10, 19],
       [13, 17, 19, 10]])

In [33]:
b[0:2]

array([[19, 15, 19, 17],
       [11, 11, 11, 15]])

In [34]:
b

array([[19, 15, 19, 17],
       [11, 11, 11, 15],
       [15, 13, 11, 12],
       [10, 19, 10, 19],
       [13, 17, 19, 10]])

In [35]:
b[0:-1]

array([[19, 15, 19, 17],
       [11, 11, 11, 15],
       [15, 13, 11, 12],
       [10, 19, 10, 19]])

In [36]:
b[0,2]

19

In [37]:
np.random.randint(10,20,(4,4))

array([[12, 11, 15, 12],
       [11, 13, 11, 19],
       [13, 11, 13, 13],
       [17, 16, 17, 13]])

OPERATIONS

In [39]:
a=np.random.randint(10,20,10)

In [40]:
a

array([15, 18, 15, 13, 10, 10, 10, 16, 15, 17])

In [41]:
id(a)

140445702086544

In [42]:
arr

array([0, 1, 2, 3, 4, 5])

In [44]:
arr2=np.random.randint(0,100,(10,10))

In [45]:
arr2

array([[61, 34, 16, 25, 35, 96, 58, 64,  6, 31],
       [54, 88, 52, 96,  4, 94, 63, 66, 20, 10],
       [83, 20, 58, 99, 77, 50, 32,  6, 14, 97],
       [57, 94, 59, 24, 11, 74,  5, 12, 68, 51],
       [89, 91, 98, 19, 92, 44, 90, 45, 61,  7],
       [66, 89, 59, 43, 37, 78, 45,  5, 25, 58],
       [48, 58, 81, 72,  0,  8, 44, 96, 14, 68],
       [17, 46, 17, 90, 94, 44, 66, 32, 63, 91],
       [92, 83, 29, 60, 37, 27, 69, 69, 91, 63],
       [98, 10, 61, 44, 84, 86,  7, 14, 93,  7]])

In [46]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [47]:
arr2[:]

array([[61, 34, 16, 25, 35, 96, 58, 64,  6, 31],
       [54, 88, 52, 96,  4, 94, 63, 66, 20, 10],
       [83, 20, 58, 99, 77, 50, 32,  6, 14, 97],
       [57, 94, 59, 24, 11, 74,  5, 12, 68, 51],
       [89, 91, 98, 19, 92, 44, 90, 45, 61,  7],
       [66, 89, 59, 43, 37, 78, 45,  5, 25, 58],
       [48, 58, 81, 72,  0,  8, 44, 96, 14, 68],
       [17, 46, 17, 90, 94, 44, 66, 32, 63, 91],
       [92, 83, 29, 60, 37, 27, 69, 69, 91, 63],
       [98, 10, 61, 44, 84, 86,  7, 14, 93,  7]])

In [48]:
arr.max()

5

In [49]:
arr.min()

0

In [50]:
arr.mean()

2.5

In [51]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [55]:
from numpy import *
a=array([1,2,3,4,9])
median(a)

3.0

In [56]:
arr

array([0, 1, 2, 3, 4, 5])

In [57]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [58]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [60]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [52]:
np.median(arr)

2.5

In [53]:
np.median(arr2)

58.0

In [61]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [62]:
arr.reshape(2,3,order='F')# rows changes to columns and columns changes to rows

array([[0, 2, 4],
       [1, 3, 5]])

In [63]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

#INDEXING

In [65]:
mat=np.arange(0,100).reshape(10,10)

In [66]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [67]:
row=4
col=5
row

4

In [68]:
col

5

In [69]:
mat[row,col]

45

In [70]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [71]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [72]:
mat[-1:]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [73]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [74]:
mat[-1:0]

array([], shape=(0, 10), dtype=int64)

In [75]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [76]:
mat[2:-2]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [77]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [78]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [79]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [80]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [82]:
mat[2:6,2:4]# 2:6 =row and 2:4=col

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [83]:
mat[1:2,2:4]

array([[12, 13]])

In [84]:
mat[2:3,2:3]

array([[22]])

In [85]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [ ]:
#MASKING

In [87]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [88]:
id(mat)

140445702543856

In [89]:
mat<50  # it checks the each element and compare if the value of element is less than 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [90]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [91]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [92]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [94]:
mat[mat==50]

array([50])

In [95]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [96]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])