NUMPY CRASH COURSE

In [1]:
import numpy as np
from numpy import * # internally it called all 217 functions

In [2]:
np.__version__

'1.21.5'

CREATING ARRAYS

In [3]:
MY_LIST=[0,1,2,3,4,5]
MY_LIST

[0, 1, 2, 3, 4, 5]

In [4]:
type(MY_LIST)

list

In [5]:
arr=np.array(MY_LIST)

In [6]:
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(3.0)

array([0., 1., 2.])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(0,5,4,3) # atleast one argument and max is three allowed

TypeError: Cannot interpret '3' as a data type

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(20,10) # first element should always less than second element.
# giving empty array

array([], dtype=int64)

In [16]:
np.arange(-10,10)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [17]:
np.arange(-10,10,5)

array([-10,  -5,   0,   5])

In [18]:
np.arange(30,20) # ist arg always be < than 2nd arg

array([], dtype=int64)

In [19]:
b=np.arange(-30,20)

In [20]:
b

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [21]:
type(b)

numpy.ndarray

In [22]:
dtype(b)

NameError: name 'dtype' is not defined

In [23]:
np.arange(10,10)

array([], dtype=int64)

ZEROS

In [31]:
b1=np.zeros(2)
b1

array([0., 0.])

In [33]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [37]:
z=np.zeros((2,2),dtype=int)
z

array([[0, 0],
       [0, 0]])

In [38]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [41]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [44]:
np.zeros((5,10)) #first arg is row and second arg is columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
n=(5,7)
n2=(6,8)
print(np.zeros(n)) # parameter tunning
print(np.zeros(n,dtype=int)) # hyperparameter tunning

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [51]:
print(np.zeros(n2))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


ONES

In [52]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [54]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [55]:
n

(5, 7)

In [56]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [57]:
np.ones(n,dtype=int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [58]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [59]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [62]:
np.arange(3)

array([0, 1, 2])

In [63]:
range(13)

range(0, 13)

In [64]:
list(range(13))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [65]:
l=list(range(10))

In [66]:
for i in l:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [67]:
rand(3,2)

NameError: name 'rand' is not defined

In [68]:
random.rand(3,2)

NameError: name 'random' is not defined

In [69]:
np.random.rand(3,2)

array([[0.81104874, 0.15741737],
       [0.16142192, 0.47190552],
       [0.57926183, 0.04984961]])

In [70]:
np.random.rand(4)

array([0.43014069, 0.08566308, 0.80084902, 0.03438043])

In [71]:
np.random.rand(2,4)

array([[0.39915629, 0.30161389, 0.34376533, 0.47000189],
       [0.37939825, 0.49184499, 0.08003487, 0.45523014]])

In [72]:
np.random.rand(2,20) # 2nd element is exclusive

array([[0.47203456, 0.30865379, 0.59179619, 0.3560756 , 0.48578084,
        0.39388406, 0.45790112, 0.21983963, 0.09730902, 0.18240511,
        0.79785826, 0.95974306, 0.37077709, 0.96332949, 0.32504631,
        0.91874581, 0.66317399, 0.84830252, 0.30403459, 0.56010491],
       [0.34606687, 0.49856989, 0.06873041, 0.97809046, 0.12647709,
        0.98302558, 0.59175826, 0.25947717, 0.16529953, 0.13534569,
        0.10118818, 0.9237936 , 0.81936614, 0.66298955, 0.99779072,
        0.04208428, 0.99284745, 0.9999189 , 0.36004668, 0.87941515]])

In [74]:
np.random.randint(0,2)

0

In [75]:
np.random.randint(1,10,4)

array([9, 7, 7, 1])

In [76]:
np.random.randint(30,30,10)

ValueError: low >= high

In [77]:
np.random.randint(1)

0

In [78]:
np.random.randint(5,9)

6

In [79]:
np.random.randint(10,21,3)

array([20, 10, 11])

In [80]:
np.random.randint(10,40,(10,10))

array([[23, 36, 25, 17, 38, 23, 20, 17, 14, 14],
       [12, 19, 27, 20, 16, 13, 12, 19, 13, 12],
       [27, 18, 31, 34, 18, 11, 13, 19, 32, 17],
       [10, 38, 31, 16, 33, 32, 36, 32, 38, 37],
       [25, 34, 23, 24, 34, 15, 35, 32, 26, 13],
       [25, 37, 27, 10, 24, 23, 10, 26, 33, 37],
       [34, 28, 25, 26, 17, 10, 36, 18, 17, 10],
       [10, 21, 10, 30, 29, 10, 38, 39, 35, 32],
       [28, 26, 11, 24, 37, 39, 34, 25, 17, 31],
       [26, 37, 29, 26, 22, 25, 28, 26, 14, 26]])

In [81]:
b=np.random.randint(10,20,(5,4))

In [82]:
b

array([[14, 18, 15, 17],
       [17, 15, 13, 15],
       [18, 18, 19, 12],
       [10, 13, 12, 13],
       [16, 12, 15, 16]])

In [83]:
b[:]

array([[14, 18, 15, 17],
       [17, 15, 13, 15],
       [18, 18, 19, 12],
       [10, 13, 12, 13],
       [16, 12, 15, 16]])

In [84]:
b[0:2]

array([[14, 18, 15, 17],
       [17, 15, 13, 15]])

In [85]:
b

array([[14, 18, 15, 17],
       [17, 15, 13, 15],
       [18, 18, 19, 12],
       [10, 13, 12, 13],
       [16, 12, 15, 16]])

In [86]:
b[0:-1]

array([[14, 18, 15, 17],
       [17, 15, 13, 15],
       [18, 18, 19, 12],
       [10, 13, 12, 13]])

In [87]:
b[0,2]

15

In [88]:
np.random.randint(10,20,(4,4))

array([[14, 18, 19, 10],
       [13, 10, 10, 13],
       [11, 14, 11, 11],
       [16, 15, 19, 10]])